import type { Level } from "@/types/game";

export const levels: Level[] = [
  {
    id: 1,
    name: "初识光线",
    gridSize: { width: 6, height: 6 },
    bestSteps: 1,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 2 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 5, y: 2 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 3, y: 2 },
        movable: true,
      },
    ],
  },
  {
    id: 2,
    name: "第一次反射",
    gridSize: { width: 6, height: 6 },
    bestSteps: 1,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 2 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 3, y: 0 },
        movable: false,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 3, y: 2 },
        orientation: "\\",
        movable: true,
      },
    ],
  },
  {
    id: 3,
    name: "绕过障碍",
    gridSize: { width: 7, height: 7 },
    bestSteps: 2,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 3 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 6, y: 3 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 3, y: 3 },
        movable: false,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 2, y: 3 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 4, y: 1 },
        orientation: "\\",
        movable: true,
      },
    ],
  },
  {
    id: 4,
    name: "双镜反射",
    gridSize: { width: 8, height: 6 },
    bestSteps: 2,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 0 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 7, y: 5 },
        movable: false,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 4, y: 0 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 4, y: 5 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 5,
    name: "移动挡板",
    gridSize: { width: 7, height: 7 },
    bestSteps: 3,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 3 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 6, y: 3 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 3, y: 3 },
        movable: true,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 2, y: 1 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 5, y: 1 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 6,
    name: "迷宫挑战",
    gridSize: { width: 8, height: 8 },
    bestSteps: 4,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 7 },
        direction: "up",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 7, y: 0 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 3, y: 4 },
        movable: false,
      },
      {
        id: "blocker-2",
        type: "blocker",
        position: { x: 4, y: 3 },
        movable: false,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 0, y: 3 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 5, y: 3 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-3",
        type: "mirror",
        position: { x: 5, y: 0 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 7,
    name: "四角反射",
    gridSize: { width: 8, height: 8 },
    bestSteps: 4,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 0 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 0, y: 7 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 4, y: 4 },
        movable: false,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 7, y: 0 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 7, y: 7 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-3",
        type: "mirror",
        position: { x: 3, y: 7 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-4",
        type: "mirror",
        position: { x: 3, y: 3 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 8,
    name: "障碍重重",
    gridSize: { width: 9, height: 7 },
    bestSteps: 5,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 3 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 8, y: 3 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 2, y: 3 },
        movable: false,
      },
      {
        id: "blocker-2",
        type: "blocker",
        position: { x: 4, y: 3 },
        movable: false,
      },
      {
        id: "blocker-3",
        type: "blocker",
        position: { x: 6, y: 3 },
        movable: false,
      },
      {
        id: "blocker-4",
        type: "blocker",
        position: { x: 3, y: 1 },
        movable: true,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 1, y: 3 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 1, y: 0 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-3",
        type: "mirror",
        position: { x: 5, y: 0 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-4",
        type: "mirror",
        position: { x: 5, y: 6 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-5",
        type: "mirror",
        position: { x: 8, y: 6 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 9,
    name: "双光源头",
    gridSize: { width: 9, height: 9 },
    bestSteps: 3,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 0 },
        direction: "right",
        movable: false,
      },
      {
        id: "light-2",
        type: "light",
        position: { x: 0, y: 8 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 8, y: 4 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 4, y: 4 },
        movable: true,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 4, y: 0 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 4, y: 8 },
        orientation: "/",
        movable: true,
      },
    ],
  },
  {
    id: 10,
    name: "终极挑战",
    gridSize: { width: 10, height: 10 },
    bestSteps: 6,
    elements: [
      {
        id: "light-1",
        type: "light",
        position: { x: 0, y: 5 },
        direction: "right",
        movable: false,
      },
      {
        id: "target-1",
        type: "target",
        position: { x: 9, y: 5 },
        movable: false,
      },
      {
        id: "blocker-1",
        type: "blocker",
        position: { x: 5, y: 5 },
        movable: false,
      },
      {
        id: "blocker-2",
        type: "blocker",
        position: { x: 3, y: 3 },
        movable: false,
      },
      {
        id: "blocker-3",
        type: "blocker",
        position: { x: 7, y: 7 },
        movable: false,
      },
      {
        id: "blocker-4",
        type: "blocker",
        position: { x: 2, y: 7 },
        movable: true,
      },
      {
        id: "blocker-5",
        type: "blocker",
        position: { x: 8, y: 2 },
        movable: true,
      },
      {
        id: "mirror-1",
        type: "mirror",
        position: { x: 2, y: 5 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-2",
        type: "mirror",
        position: { x: 2, y: 1 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-3",
        type: "mirror",
        position: { x: 6, y: 1 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-4",
        type: "mirror",
        position: { x: 6, y: 9 },
        orientation: "\\",
        movable: true,
      },
      {
        id: "mirror-5",
        type: "mirror",
        position: { x: 9, y: 9 },
        orientation: "/",
        movable: true,
      },
      {
        id: "mirror-6",
        type: "mirror",
        position: { x: 9, y: 2 },
        orientation: "\\",
        movable: true,
      },
    ],
  },
];
